from random import randint
from Gerador_Walden import fisico
from Gerador_Walden import rosto
from Gerador_Walden import pele
from Gerador_Walden import vestimenta
from Gerador_Walden import fala
from Gerador_Walden import vicio
from Gerador_Walden import cabelo
from Gerador_Walden import virtude